version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: 'fix(deps): '
    groups:
      all:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: 'fix(deps): '
    groups:
      all:
        patterns:
          - '*'
    ignore:
      - dependency-name: typescript
        update-types: [version-update:semver-minor]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: 'fix(deps): '
    groups:
      all:
        patterns:
          - '*'
