name: App Release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/check-manifest
      - uses: shopware/github-actions/store-release@main
        with:
          extensionName: SwagBraintreeApp
          publishOnly: 'true'
          accountUser: ${{ secrets.SHOPWARE_ACCOUNT_USER }}
          accountPassword: ${{ secrets.SHOPWARE_ACCOUNT_PASSWORD }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}
