name: JS

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.ts'
      - package.json
      - package-lock.json
      - .github/actions/setup-node/action.yml
      - .github/workflows/js.yml
  push:
    paths:
      - '**/*.js'
      - '**/*.ts'
      - package.json
      - package-lock.json
      - .github/actions/setup-node/action.yml
      - .github/workflows/js.yml
    branches:
      - trunk

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Run ESLint
        run: npm run eslint -- --output-file eslint-report.json --format json
        continue-on-error: true
      - name: ESLint report to cli
        run: node -p "require('./node_modules/eslint/lib/cli-engine/formatters/stylish.js')(require('./eslint-report.json'))"
      - name: Annotate ESLint report
        uses: ataylorme/eslint-annotate-action@v3
        with:
          report-json: eslint-report.json

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Run ESLint
        run: npm run tsc

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Run vite
        run: npm run build
