name: Meta
on:
  workflow_dispatch:
  pull_request:

jobs:
  app-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check-manifest
      - uses: shopware/github-actions/build-zip@main
        with:
          extensionName: SwagBraintreeApp

  manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-php
      - uses: ./.github/actions/check-manifest
      - name: Generate manifest.xml
        run: composer setup:manifest -- -f --env=prod
      - uses: ./.github/actions/check-manifest
      - name: Check manifest.xml
        run: |
          git update-index --refresh || printf ''
          git diff-index "${{ github.sha }}" --quiet -- manifest.xml || (echo "Please run 'APP_ENV=prod composer setup:manifest' to sync the manifest.xml" && exit 1)

  doctrine:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.5
        env:
          MARIADB_ROOT_PASSWORD: swagbraintree
          MYSQL_DATABASE: swagbraintree
        ports: ['3306:3306']
    env:
      DATABASE_URL: mysql://root:swagbraintree@127.0.0.1:3306/swagbraintree
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-php

      - name: Migrate database
        run: bin/console doctrine:migrations:migrate --no-interaction

      - name: Validate doctrine schema
        run: bin/console doctrine:schema:validate --verbose