name: PHP
on:
  pull_request:
    paths:
      - '**/*.php'
      - composer.json
      - .github/workflows/php.yml
  push:
    paths:
      - '**/*.php'
      - composer.json
      - .github/workflows/php.yml
    branches:
      - trunk
  workflow_dispatch:

jobs:
  ecs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Run ECS
        run: composer ecs

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Generate PHPStan cache
        run: php bin/console cache:clear
      - name: Run PHPStan
        run: composer phpstan

  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: pcov
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Run PHPUnit
        run: composer phpunit -- --coverage-clover=coverage.xml
      - name: Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml

  infection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: pcov
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Run Infection
        run: composer infection -- --min-msi=95
        env:
          INFECTION_DASHBOARD_API_KEY: ${{ secrets.INFECTION_DASHBOARD_API_KEY }}