name: PHP

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.php'
      - '*.dist'
      - composer.json
      - composer.lock
      - symfony.lock
      - infection.json5
      - .php-cs-fixer.dist.php
      - phpstan.neon
      - .github/workflows/php.yml
  push:
    paths:
      - '**/*.php'
      - '*.dist'
      - composer.json
      - composer.lock
      - symfony.lock
      - infection.json5
      - .php-cs-fixer.dist.php
      - phpstan.neon
      - .github/workflows/php.yml
    branches:
      - trunk

jobs:
  ecs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-php
      - name: Run ECS
        run: composer ecs

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-php
      - name: Generate PHPStan cache
        run: php bin/console cache:clear
      - name: Run PHPStan
        run: composer phpstan

  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-php
      - name: Run PHPUnit
        run: composer phpunit -- --coverage-clover=coverage.xml
      - name: Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml

  infection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-php
      - name: Run Infection
        run: composer infection -- --min-msi=95
        env:
          INFECTION_DASHBOARD_API_KEY: ${{ secrets.INFECTION_DASHBOARD_API_KEY }}

  doctrine:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.5
        env:
          MARIADB_ROOT_PASSWORD: swagbraintree
          MYSQL_DATABASE: swagbraintree
        ports: ['3306:3306']
    env:
      DATABASE_URL: mysql://root:swagbraintree@127.0.0.1:3306/swagbraintree
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-php

      - name: Migrate database
        run: bin/console doctrine:migrations:migrate --no-interaction

      - name: Validate doctrine schema
        run: bin/console doctrine:schema:validate --verbose
